#!/bin/bash

Resources for Basic AWS:
================
these below 2 are inter related...
Theory: https://github.com/iam-veeramalla/aws-devops-zero-to-hero
Videos: https://www.youtube.com/playlist?list=PLdpzxOOAlwvLNOxX0RfndiYSt1Le9azze


===========================================
       WELCOME TO AWS NOTES
===========================================

to write a script - to create a resource like EC2 or VM

-> AWS CLI
-> AWS API (Boto 3)
-> AWS CFT 
 other tool used to terraform (maintained by hashycop)
these tools will connect directly to API to create infrastructure creartion
all are choosing hybrid cloud model -things to automate terraform is best tool which intteracts with multiple cloud

===========

to access the instacce in mobaxterm

--> ssh -i <give the pem file path> username@ip

<chmod 600 <file path name>>  - this command to change the file permissions private

command to create an s3 thorugh cli:
cmd:'aws s3 mb s3://vetsabucket3 --region us-west-2'


======================================================
-------------********AWS ECR NOTES******------------------
ECR - elastic contanier registry

it is similar to docker hub
quay.io  private
gcr
which means to store the images

elastic means moslty highly scalable and avilablity in aws

diff b/w ecr and docker hub
docker is free and default will be public repos
ecr supports by deafult it will private nature
ecr is very easy intergration with other serivces like eks and others

&&this is not a free service

demoo:
in ecr - create repository
keep a private and it is access are managed by IAM
provide the repo name
enable the tag immuity
enable the image scan setting
to push aws is giving the see the view push commands from thewre we can push docker images into registry
go to aws cli and confifure using the aws configure
login to ecr using the aws ecr command
(by default docker have docker login command)
make sure provide proper policy attached
after login 
create a docker file
docker build to image
docker tag
docker push 

after this we will access directly our image in the ecr


==========================================================================
